Make pyinfra compatible with `uv`
`uv` requires `pyproject.toml`, so previously trying to use `uv` against pyinfra resulted in:

```
$ uv run --extra dev mypy -p pyinfra
error: No `project` table found in: `/pyinfra/pyproject.toml`
```

After adding minimal `[project]` section to `pyproject.toml`, `uv` commands run succesfully.

Testing: to make sure the change doesn't introduce any visible changes to the package:

- built wheels on current `3.x` branch and on my branch via `python3 setup.py bdist_wheel`
- unpacked via `unzip`
- compared recursively via `diff -bur dist_old/ dist_new/`

This results in exact match, i.e. all package metadata is unchanged as expected.