Show error when generating askpass command fails
If no sudo_askpass_path is set, pyinfra generates an askpass script
remotely. When this would fail and no stdout was generated, this would
produce:

        --> An internal exception occurred:
          File "/.../pyinfra/connectors/util.py", line 280, in _ensure_sudo_askpass_set_for_host
            host.connector_data["sudo_askpass_path"] = shlex.quote(output.stdout_lines[0])
                                                                   ~~~~~~~~~~~~~~~~~~~^^^
        IndexError: list index out of range

With this commit, the output is more useful:

        --> pyinfra error: Failed to create sudo_askpass command: WARNING: Your password has expired.
        Password change required but no TTY available.

Or:

        --> pyinfra error: Failed to create sudo_askpass command: no output produced by command: [stderr output here]